'use client';

import { useEffect, useState } from 'react';

// ─── Types ────────────────────────────────────────────────────────────────────

export type JobStatus = 'ok' | 'error' | 'stale' | 'no_log';

export interface ScheduledJob {
  key: string;
  label: string;
  schedule: string;
  status: JobStatus;
  last_run_iso: string | null;
  last_line: string;
  alert_count: number;
}

export interface ScheduledStatusSummary {
  total: number;
  ok: number;
  error: number;
  stale: number;
  no_log: number;
}

export interface ScheduledStatusData {
  _meta: {
    generated: string;
    reporter_version: string;
  };
  jobs: ScheduledJob[];
  summary: ScheduledStatusSummary;
}

export interface UseScheduledStatusResult {
  data: ScheduledStatusData | null;
  isLoading: boolean;
  fetchError: string | null;
}

// ─── Hook ─────────────────────────────────────────────────────────────────────

/**
 * useScheduledStatus — fetches /scheduled_status.json client-side.
 *
 * Independent of data.json. Generated by scripts/scheduled_reporter.py
 * (LaunchAgent io.fdte.scheduled-reporter, seg–sex 7h25).
 *
 * Issue: DEV-scheduled-status
 */
export function useScheduledStatus(): UseScheduledStatusResult {
  const [data, setData] = useState<ScheduledStatusData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [fetchError, setFetchError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function load() {
      try {
        const res = await fetch('/scheduled_status.json', {
          // Revalidate on each load — file updates daily
          cache: 'no-store',
        });
        if (!res.ok) {
          throw new Error(`HTTP ${res.status}`);
        }
        const json = (await res.json()) as ScheduledStatusData;
        if (!cancelled) {
          setData(json);
          setFetchError(null);
        }
      } catch (err) {
        if (!cancelled) {
          setFetchError(err instanceof Error ? err.message : 'Fetch error');
        }
      } finally {
        if (!cancelled) setIsLoading(false);
      }
    }

    load().catch(() => {});

    return () => {
      cancelled = true;
    };
  }, []);

  return { data, isLoading, fetchError };
}
