// Dashboard Changelog — rastreamento de alterações visíveis no dashboard
// REGRA: antes de qualquer commit em react-app/src/, o dev agent DEVE adicionar
// entrada aqui (mais recente no topo). Veja CLAUDE.md → Changelog de Componentes.

export type ChangeType = 'layout' | 'dado' | 'gráfico' | 'cálculo' | 'visual';

export interface ChangelogEntry {
  datetime: string;   // ISO '2026-04-27T20:48'
  type: ChangeType;
  component: string;  // nome legível do componente
  tab: string;        // rota sem barra: 'performance' | 'fire' | 'backtest' | 'portfolio' | 'withdraw' | 'assumptions' | 'now'
  anchor: string;     // id da seção, sem '#' (vazio = só a aba)
  de: string;         // estado anterior
  para: string;       // estado novo
}

export const CHANGELOG: ChangelogEntry[] = [
  // ── 2026-04-28 — Gap U: Factor Value Spread widget (AQR HML Devil, proxy 58/42) ──
  { datetime: '2026-04-28T23:00:00', type: 'dado', component: 'Factor Value Spread', tab: 'portfolio', anchor: '', de: '—', para: 'widget semáforo value spread AVGS — AQR HML Devil + KF SMB, proxy 58/42, status P42 neutro (wide >P75, compressed <P25)' },
  // ── 2026-04-28 — ContributionReturnsCrossover: EC colors + axis theme padrão ──
  { datetime: '2026-04-28T22:45:00', type: 'visual', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: 'CSS vars (var(--muted), var(--yellow)) nas séries e eixos sem theme padrão', para: 'EC.muted / EC.yellow (hex canvas-safe), EC_AXIS_LINE + EC_SPLIT_LINE + EC_TOOLTIP + EC_AXIS_LABEL em todos os eixos' },
  // ── 2026-04-28 — ContributionReturnsCrossover: UI fixes (tooltip K, legenda bottom, banda, label) ──
  { datetime: '2026-04-28T22:30:00', type: 'visual', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: 'tooltip em M ("R$ R$0M"), legenda top, banda opacity 8%, sub-label "VALOR ABSOLUTO" desnecessário, card "Aporte Anual Modelo"', para: 'tooltip pvLabel() nativo (R$392k), legenda bottom, banda 15%, sub-label removido, card renomeado para "Aporte Anual"' },
  // ── 2026-04-28 — ContributionReturnsCrossover: remove flywheel (%) sub-chart ──
  { datetime: '2026-04-28T22:10:00', type: 'gráfico', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: '2 gráficos: Valor Absoluto R$ + Flywheel % do Patrimônio', para: '1 gráfico apenas: Valor Absoluto R$ — flywheel removido por decisão do FIRE agent (tendências díspares causavam confusão sem valor de decisão)' },
  // ── 2026-04-28 — ContributionReturnsCrossover: contexto histórico + estimativa 2026 ──
  { datetime: '2026-04-28T09:10:00', type: 'dado', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: '2026 como "parcial" sem distinção de tipo; 2021/2022 sem distinção de capital inicial; projeção sobrepunha 2026', para: '2026 como "estimado" (†) com nota Jan–Abr realizado + Mai–Dez @ R$25k/mês 9% nominal; 2021 capital_inicial=R$252k (XP), 2022 capital_inicial=R$72k (FIIs); projeção começa 2027; diamante amarelo nos anos com capital não-DCA; tooltip enriquecido' },
  // ── 2026-04-28 — ContributionReturnsCrossover: 4 fixes (legenda, toggle, 2026 parcial, ganho_rate 2021) ─
  { datetime: '2026-04-28T08:55:00', type: 'gráfico', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: 'legenda ausente, toggle residual, 2026 sem visual distinto, ganho_rate 2021 com denominador errado', para: 'legenda explícita (Rentabilidade Anual / Aportes Anuais), toggle removido do build, 2026* com opacidade 50% e aviso no tooltip, ganho_rate 2021=null no pipeline (linha % começa em 2022)' },
  // ── 2026-04-28 — ContributionReturnsCrossover: remove toggle + add flywheel chart ─
  { datetime: '2026-04-28T21:30:00', type: 'gráfico', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: 'toggle nominal/real + 1 chart R$ absoluto', para: 'sem toggle (nominal fixo), 2 charts: Valor Absoluto (R$) + Flywheel % do Patrimônio; pipeline adiciona aporte_rate e ganho_rate' },
  // ── 2026-04-28 — ContributionReturnsCrossover + P(FIRE) boxplot fix ─────────
  { datetime: '2026-04-28T20:00:00', type: 'gráfico', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: 'não existia', para: 'Crossover Point — rentabilidade anual R$ vs aporte anual R$, histórico 2021-2026 + projeção 3 cenários, toggle nominal/real, marcador de crossover' },
  { datetime: '2026-04-28T20:00:00', type: 'dado', component: 'PFireDistribution', tab: 'fire', anchor: '', de: 'percentis bootstrap range 0.87pp (source: mc)', para: 'percentis por sensitivity_scenarios range 8pp (p5=82.1% p95=90.1%, source: sensitivity_scenarios)' },
  // ── 2026-04-28 — HD-dashboard-gaps-tier2 ────────────────────────────────────
  { datetime: '2026-04-28T16:00:00', type: 'dado', component: 'RendaPlusMtmPnl', tab: 'portfolio', anchor: 'section-renda-plus-mtm', de: 'sem MtM da Renda+', para: 'Gap S: card taxa entrada/atual + P&L MtM em R$ e % (data-testid="renda-plus-mtm-pnl")' },
  { datetime: '2026-04-28T18:00:00', type: 'visual', component: 'SpendingCeiling', tab: 'fire', anchor: 'section-spending-ceiling', de: 'valores em formato R$ 136.000', para: 'valores em formato compacto R$ 136k + valor mensal por card (R$ 11k/mês)' },
  { datetime: '2026-04-28T16:00:00', type: 'cálculo', component: 'BreakevenIpcaSelic', tab: 'portfolio', anchor: 'section-breakeven-ipca-selic', de: 'sem break-even IPCA+ vs Selic', para: 'Gap Q: break-even líquido de IR + tabela acumulação 10 anos (data-testid="breakeven-year-ipca-selic")' },
  { datetime: '2026-04-28T16:00:00', type: 'dado', component: 'VolRealizadaVsMC', tab: 'performance', anchor: '', de: 'sem vol realizada', para: 'Gap O: volatilidade anualizada 12m vs premissa MC com badge ⚠/✓ (data-testid="vol-realizada-vs-mc")' },
  { datetime: '2026-04-28T16:00:00', type: 'dado', component: 'BondPoolStatus', tab: 'fire', anchor: '', de: 'sem status bond pool', para: 'Gap M: progress bar IPCA+2040+2050 vs meta 7 anos de gastos (data-testid="bond-pool-status")' },
  { datetime: '2026-04-28T16:00:00', type: 'cálculo', component: 'RetornoCambialDecomposicao', tab: 'performance', anchor: '', de: 'sem decomposição cambial', para: 'Gap R: USD + FX = BRL com interpretação FX positivo/negativo (data-testid="retorno-cambial-decomposicao")' },
  { datetime: '2026-04-28T16:00:00', type: 'dado', component: 'SpendingCeiling', tab: 'fire', anchor: 'section-spending-ceiling', de: 'sem spending ceiling analítico', para: 'Gap L: 3 tiers P90/P85/P80 com SWR correspondente (data-testid="spending-ceiling")' },
  { datetime: '2026-04-28T16:00:00', type: 'cálculo', component: 'PFireSensitivity', tab: 'fire', anchor: 'section-pfire-sensitivity', de: 'sem tabela de sensibilidade P(FIRE)', para: 'Gap N: tabela 7 linhas com variável/base/stress/delta (data-testid="pfire-sensitivity-table")' },
  { datetime: '2026-04-28T16:00:00', type: 'dado', component: 'CorrelacaoStress', tab: 'portfolio', anchor: 'section-correlation-stress', de: 'sem correlação em stress', para: 'Gap P: normal vs stress (meses retorno<-5%) para equity-RF e equity-FX (data-testid="correlation-matrix-stress")' },
  // ── 2026-04-28 — HD-dashboard-gaps-tier1 ────────────────────────────────────
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'PatrimonioLiquidoIR', tab: 'now', anchor: 'section-patrimonio-liquido-ir', de: 'sem P(FIRE) líquido', para: 'Gap C: exibe P(FIRE) Líquido e Bruto de fire_montecarlo_liquido (data-testid="pfire-liquido")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'FIRENumberMeta', tab: 'fire', anchor: '', de: 'sem FIRE Number explícito', para: 'Gap G: FIRE Number com meta/atual/gap e barra de progresso (data-testid="fire-number-meta")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'RiskSemaforos', tab: 'now', anchor: 'risk-semaforos', de: '3 semáforos sem CDS', para: 'Gap B: CDS Brasil 5Y adicionado ao R2 como 4º semáforo (data-testid="cds-brasil-semaforo")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'BalancoHolistico', tab: 'now', anchor: 'section-balanco-holistico', de: 'balanço holístico só em FIRE tab', para: 'Gap A: seção colapsável no NOW tab com breakdown 5 componentes (data-testid="balanco-holistico")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'RendaPlusGatilho', tab: 'portfolio', anchor: '', de: 'sem widget dedicado Renda+', para: 'Gap D: widget taxa atual vs gatilho DCA com distância em bps e status (data-testid="renda-plus-gatilho")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'RendaFloorKatia', tab: 'fire', anchor: '', de: 'sem nota sobre renda Katia', para: 'Gap F: card Renda Floor Katia com INSS, P(FIRE) aspiracional e nota conservadora (data-testid="renda-floor-katia")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'FactorDroughtCounter', tab: 'portfolio', anchor: '', de: 'sem contador de drought fatorial', para: 'Gap H: badge AVGS vs SWRD com excess YTD, excess since launch e contexto histórico (data-testid="factor-drought-counter")' },
  { datetime: '2026-04-28T12:00:00', type: 'layout', component: 'ExposicaoGeografica', tab: 'portfolio', anchor: 'section-etf-region', de: 'data-testid="geo-donut"', para: 'Gap E: renomeado para data-testid="exposicao-geografica" (correto segundo spec)' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'DrawdownContextBanner', tab: 'performance', anchor: '', de: 'sem banner de drawdown contextual', para: 'Gap J: banner condicional quando drawdown>5% com guardrail e ação recomendada (data-testid="drawdown-context-banner")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'IPSSummary', tab: 'now', anchor: 'section-ips-summary', de: 'sem IPS summary', para: 'Gap K: card com 7 regras do IPS (equity alvo, SWR, pisos, guardrail, CDS, drift) de data.json (data-testid="ips-summary")' },
  // ── 2026-04-28 — risk_metrics fixes ─────────────────────────────────────────
  { datetime: '2026-04-28T00:00:00', type: 'cálculo', component: 'RiskDashboard', tab: 'portfolio', anchor: '', de: 'ModDur hardcoded 43.25, EQUITY_PCT hardcoded 0.79, semáforo drift hardcoded verde', para: 'ModDur lido de rf.renda2065.duration (fallback 46.24 ANBIMA), equity_pct de drift.atual, drift semáforo lê max deviation real' },
  { datetime: '2026-04-28T00:00:00', type: 'dado', component: 'RiskDashboard', tab: 'portfolio', anchor: 'section-duration-scenarios', de: 'tabela duration sem contexto proporcional; MtM exibido como % título sem % portfólio', para: 'coluna % do Portfólio (mtm × peso Renda+) + nota "posição tática ~3.4%"' },
  { datetime: '2026-04-28T00:00:00', type: 'dado', component: 'RiskDashboard', tab: 'fire', anchor: 'section-sorr-indicator', de: 'SoRR valores estáticos sem sinalização; baseline P(FIRE) implícito', para: 'caption "estimativa estática" + baseline dinâmico do MC (sorr_base_pfire)' },
  { datetime: '2026-04-28T00:00:00', type: 'dado', component: 'RiskDashboard', tab: 'portfolio', anchor: 'section-risk-contribution', de: 'nota de risco sem mencionar limitação metodológica', para: 'caption "Não considera correlação entre ativos"' },
  // ── 2026-04-27 — HD-risco-portfolio ─────────────────────────────────────────
  { datetime: '2026-04-27T00:00:00', type: 'gráfico', component: 'RiskDashboard', tab: 'now', anchor: '', de: 'sem visão de risco consolidada', para: 'Risk Score gauge + semáforos de alertas (R1+R2)' },
  { datetime: '2026-04-27T00:00:00', type: 'gráfico', component: 'RiskDashboard', tab: 'portfolio', anchor: '', de: 'sem visão de risco', para: 'Risk Contribution chart + Duration Scenarios table (R3+R4)' },
  { datetime: '2026-04-27T00:00:00', type: 'dado', component: 'RiskDashboard', tab: 'performance', anchor: '', de: 'sem monitor de drawdown', para: 'Drawdown Monitor com badge de guardrail (R5)' },
  { datetime: '2026-04-27T00:00:00', type: 'dado', component: 'RiskDashboard', tab: 'fire', anchor: '', de: 'sem indicador SoRR', para: 'SoRR Indicator com cenários de crash (R6)' },
  // ── 2026-04-27 ──────────────────────────────────────────────────────────────
  {
    datetime: '2026-04-27T20:48',
    type: 'layout',
    component: 'Retornos Mensais Heatmap',
    tab: 'performance',
    anchor: 'section-heatmap',
    de: 'posicionado após seção Análise Técnica',
    para: 'logo após Retornos Anuais',
  },
  {
    datetime: '2026-04-27T20:48',
    type: 'visual',
    component: 'SoRR — Texto Explicativo',
    tab: 'fire',
    anchor: 'sequence-returns',
    de: '3 parágrafos com referências Karsten + bond duration',
    para: '2 frases compactas (o quê é + 2 defesas)',
  },
  {
    datetime: '2026-04-27T20:35',
    type: 'dado',
    component: 'Exposição Cambial',
    tab: 'portfolio',
    anchor: 'section-brl-fx-portfolio',
    de: 'sempre 0%',
    para: 'computado de posições IBKR vivas',
  },
  {
    datetime: '2026-04-27T20:21',
    type: 'dado',
    component: 'DARF Obligations',
    tab: 'portfolio',
    anchor: 'section-darf-obligations',
    de: 'sem dados (vazio)',
    para: 'realized_pnl FIFO validado (IBKR Phase 3B)',
  },
  {
    datetime: '2026-04-27T20:04',
    type: 'gráfico',
    component: 'Stress Macroeconômico',
    tab: 'fire',
    anchor: 'section-stress-macro',
    de: 'não existia',
    para: 'card Stagflation & Hyperinflation com P(FIRE) e spending cut',
  },
  {
    datetime: '2026-04-27T20:01',
    type: 'cálculo',
    component: 'Fire Monte Carlo — Cenários',
    tab: 'fire',
    anchor: 'trackingFireSection',
    de: '2 cenários (base + IPCA+4)',
    para: '4 cenários (+ stagflation + hyperinflation)',
  },
  {
    datetime: '2026-04-27T18:56',
    type: 'dado',
    component: 'Factor Signal — Cache',
    tab: 'performance',
    anchor: 'section-etf-factor',
    de: 'sem timestamps, recalculado a cada run',
    para: 'timestamps + cache persistido em dados/',
  },
  {
    datetime: '2026-04-27T18:41',
    type: 'dado',
    component: 'P(FIRE) — Rastreabilidade',
    tab: 'fire',
    anchor: 'trackingFireSection',
    de: 'sem source / is_canonical',
    para: 'source + is_canonical em pfire_base e pfire_aspiracional',
  },
  {
    datetime: '2026-04-27T18:24',
    type: 'dado',
    component: 'Factor Signal + IR Diferido',
    tab: 'portfolio',
    anchor: 'section-tax-ir',
    de: 'ausentes em data.json',
    para: 'preenchidos (563 testes ✓)',
  },
  {
    datetime: '2026-04-27T18:08',
    type: 'gráfico',
    component: 'BTC/SWRD Correlation Chart',
    tab: 'backtest',
    anchor: 'section-btc-indicators',
    de: 'não existia',
    para: 'rolling 90d com série temporal real',
  },
  {
    datetime: '2026-04-27T17:55',
    type: 'dado',
    component: 'Decisão do Mês — Data',
    tab: 'now',
    anchor: '',
    de: '"Pendente (2026-03)"',
    para: 'data correta da última decisão aprovada',
  },
  {
    datetime: '2026-04-27T12:24',
    type: 'cálculo',
    component: 'Simuladores + FIRE Date + Attribution',
    tab: 'fire',
    anchor: 'fireAspirationalSection',
    de: 'P%, data FIRE e attribution com valores incorretos',
    para: 'todos corrigidos (v1.10.3)',
  },
  {
    datetime: '2026-04-27T10:26',
    type: 'dado',
    component: 'RF + CAGR Real + Drawdown + Imóvel',
    tab: 'performance',
    anchor: 'performanceSummarySection',
    de: 'RF Nubank, CAGR real, drawdown_extended, imóvel equity ausentes',
    para: 'todos preenchidos (v1.8.3)',
  },
  // ── 2026-04-25 ──────────────────────────────────────────────────────────────
  {
    datetime: '2026-04-25T21:12',
    type: 'gráfico',
    component: 'SoRR Heatmap — Monte Carlo',
    tab: 'fire',
    anchor: 'sequence-returns',
    de: 'placeholder vazio',
    para: 'trajetórias MC p10/p25/p50/p75/p90',
  },
  {
    datetime: '2026-04-25T21:10',
    type: 'dado',
    component: 'Focus Expectations BCB',
    tab: 'assumptions',
    anchor: 'assumptions-onde-estou',
    de: 'não existia',
    para: 'expectativas BCB Focus (IPCA, Selic, PIB, câmbio)',
  },
  {
    datetime: '2026-04-25T21:09',
    type: 'dado',
    component: 'BTC/SWRD Correlação 90d',
    tab: 'portfolio',
    anchor: 'section-crypto-band',
    de: 'não existia',
    para: 'correlação 90d exibida no painel de risco',
  },
  {
    datetime: '2026-04-25T21:06',
    type: 'visual',
    component: 'Factor Waterfall — Alpha Drought',
    tab: 'performance',
    anchor: 'section-expected-return-waterfall',
    de: 'sem nota de ressalva',
    para: 'caveat "alpha drought 2024–2025" adicionado',
  },
  {
    datetime: '2026-04-25T20:50',
    type: 'dado',
    component: 'RF Status Panel — pctAlvo',
    tab: 'portfolio',
    anchor: 'section-rf-status',
    de: 'hardcoded',
    para: 'dinâmico (taxa ANBIMA atual)',
  },
  {
    datetime: '2026-04-25T20:43',
    type: 'cálculo',
    component: 'P(FIRE) Aspiracional',
    tab: 'fire',
    anchor: 'fireAspirationalSection',
    de: 'incorreto (sem safety net)',
    para: 'corrigido + safety net documentado',
  },
  {
    datetime: '2026-04-25T17:14',
    type: 'cálculo',
    component: 'Aporte Médio',
    tab: 'now',
    anchor: 'section-rebalancing-status',
    de: 'R$68k (dupla contagem equity)',
    para: 'R$48k corrigido',
  },
  {
    datetime: '2026-04-25T18:17',
    type: 'layout',
    component: 'CollapsibleSection — Hash Navigation',
    tab: 'now',
    anchor: '',
    de: 'não abria ao navegar por URL âncora',
    para: 'auto-abre quando URL contém o hash da seção',
  },
  // ── 2026-04-24 ──────────────────────────────────────────────────────────────
  {
    datetime: '2026-04-24T23:08',
    type: 'layout',
    component: 'Decisão do Mês — Unificação',
    tab: 'now',
    anchor: '',
    de: '3 painéis separados (Aporte, DCA, Macro)',
    para: 'DecisaoDoMes unificado em 1 card',
  },
  {
    datetime: '2026-04-24T22:55',
    type: 'dado',
    component: 'Tabela Retornos Anuais',
    tab: 'performance',
    anchor: 'timelineSection',
    de: 'apenas retorno BRL por ano',
    para: '+ CAGR USD, VWRA e CDI por linha',
  },
  {
    datetime: '2026-04-24T22:34',
    type: 'dado',
    component: 'Portfolio — Binance + HODL11',
    tab: 'portfolio',
    anchor: 'section-etf-region',
    de: 'Binance sem posição real; HODL11 sem região',
    para: 'Binance integrado + HODL11 reclassificado como global',
  },
  {
    datetime: '2026-04-24T14:52',
    type: 'layout',
    component: 'FIRE Progress Card',
    tab: 'now',
    anchor: 'section-wellness',
    de: 'TimeToFire + FireProgressWellness separados',
    para: 'card único consolidado',
  },
  {
    datetime: '2026-04-24T14:45',
    type: 'dado',
    component: 'Semáforo de Saúde',
    tab: 'now',
    anchor: 'section-wellness',
    de: 'badge de status sem ação',
    para: '+ ação explícita + reorganização da home',
  },
  {
    datetime: '2026-04-24T13:21',
    type: 'cálculo',
    component: 'ReverseFire — Câmbio',
    tab: 'fire',
    anchor: 'fireAspirationalSection',
    de: 'câmbio fixo hardcoded',
    para: 'PTAX dinâmico integrado',
  },
  {
    datetime: '2026-04-24T10:32',
    type: 'cálculo',
    component: 'Monte Carlo P(FIRE) — Modelo',
    tab: 'fire',
    anchor: 'trackingFireSection',
    de: 'bootstrap heurístico',
    para: 'lognormal GBM + Ito correction (canônico)',
  },
  {
    datetime: '2026-04-24T10:12',
    type: 'gráfico',
    component: 'ReverseFire v2',
    tab: 'fire',
    anchor: 'fireAspirationalSection',
    de: 'v1 — forward sim simples',
    para: 'v2 — P(FIRE) MC + slider custo + ano no eixo',
  },
  {
    datetime: '2026-04-24T09:31',
    type: 'layout',
    component: 'Autenticação',
    tab: 'now',
    anchor: '',
    de: 'GitHub OAuth',
    para: 'SHA-256 + cookies (persistência iOS/remoto)',
  },
];
