// Dashboard Changelog — rastreamento de alterações visíveis no dashboard
// REGRA: antes de qualquer commit em react-app/src/, o dev agent DEVE adicionar
// entrada aqui (mais recente no topo). Veja CLAUDE.md → Changelog de Componentes.

export type ChangeType = 'layout' | 'dado' | 'gráfico' | 'cálculo' | 'visual' | 'fix';

export interface ChangelogEntry {
  datetime: string;   // ISO '2026-04-27T20:48'
  type: ChangeType;
  component: string;  // nome legível do componente
  tab: string;        // rota sem barra: 'performance' | 'fire' | 'backtest' | 'portfolio' | 'withdraw' | 'assumptions' | 'now'
  anchor: string;     // id da seção, sem '#' (vazio = só a aba)
  de: string;         // estado anterior
  para: string;       // estado novo
}

export const CHANGELOG: ChangelogEntry[] = [
  { datetime: '2026-05-01T04:00:00-03:00', type: 'gráfico', component: 'PostFireFanChart', tab: 'fire', anchor: 'section-fan-chart-mc', de: 'P(FIRE) exibido apenas como número — sem visualização de trajetórias', para: 'FR-fan-chart-mc: fan chart P10/P50/P90 pós-FIRE com banda sombreada (2038–2075), trajetória real/projetada pré-FIRE, linhas de FIRE Day (2040) e FIRE Number' },
  { datetime: '2026-05-01T03:00:00-03:00', type: 'gráfico', component: 'BondPoolDepletionChart', tab: 'fire', anchor: 'section-bond-pool-depletion', de: 'Sem visualização de esgotamento do bond pool pós-FIRE', para: 'FR-bond-pool-tracker: projeção determinística 2040–2055 com saldo "Meta atingida" (R$1.72M) vs "Trajetória atual" — INSS reduz saque a partir de 2049 (Katia) e 2052 (Diego)' },
  { datetime: '2026-05-01T00:00:00-03:00', type: 'fix', component: 'ChangelogTable', tab: 'assumptions', anchor: 'dashboard-updates', de: 'fmtDatetime fazia split de string — mostrava hora UTC sem converter para BRT', para: 'toLocaleString com timeZone: America/Sao_Paulo — idêntico ao formatBrt do Header' },
  { datetime: '2026-04-30T21:00:00', type: 'gráfico', component: 'DrawdownExtendedChart', tab: 'backtest', anchor: 'section-drawdown-extended', de: 'Gráfico de drawdown histórico multi-período não renderizava (drawdown_extended.periods ausente no data.json)', para: 'B10: pipeline agora computa 4 períodos — real (2021+, CSV real), medium (backtest 2019+), long (R5 2005+), academic (R7 1995+) — com dd_target_pct e dd_benchmark_pct por ponto' },
  { datetime: '2026-04-30T23:59:00', type: 'dado', component: 'NowPage', tab: 'now', anchor: '', de: 'Sem card de capital humano Katia na aba NOW', para: 'C8: mini card compacto — Cap. Humano Katia: INSS R$93.6k/ano (a partir de 2049) · PGBL FIRE R$490k · Custo solo R$160k/ano — visível quando inss_katia_anual > 0, privacy obrigatório' },
  { datetime: '2026-04-30T23:59:30', type: 'dado', component: 'BrasilConcentrationCard', tab: 'portfolio', anchor: 'section-brasil-concentration', de: 'Mostra apenas % do portfólio financeiro (10.5%)', para: 'Adiciona % do balanço holístico (inclui capital humano, INSS, imóvel, terreno) — ex: 5.1%' },
  { datetime: '2026-04-30T23:59:20', type: 'dado', component: 'DurationScenariosTable', tab: 'portfolio', anchor: 'section-duration-scenarios', de: 'Apenas cenários +1pp e +2pp (alta de taxa = perda)', para: 'Adiciona −1pp e −2pp (queda de taxa = valorização Renda+ 2065) com highlight verde' },
  { datetime: '2026-04-30T23:59:10', type: 'visual', component: 'FireSpectrumWidget', tab: 'fire', anchor: 'section-fire-spectrum', de: '"posição atual" aponta para último milestone atingido (Barista FIRE)', para: '"próxima meta" aponta para próximo milestone não atingido (Lean FIRE) — milestones já atingidos exibem só checkmark' },
  { datetime: '2026-04-30T23:59:00', type: 'gráfico', component: 'TimelineAttributionChart', tab: 'backtest', anchor: 'attribution-by-period', de: 'Sem atribuição de retorno RF/equity/FX por período', para: 'B11: stacked bar chart ECharts por ano com RF, Equity e FX/Câmbio — totais acumulados com data-testid b11-attr-rf-total / b11-attr-equity-total / b11-attr-fx-total' },
  { datetime: '2026-04-30T20:30:00', type: 'gráfico', component: 'FirePage', tab: 'fire', anchor: 'section-pfire-histogram', de: 'Sem histograma de distribuição de data FIRE', para: 'C13: CollapsibleSection com gráfico de barras ECharts mostrando probabilidade marginal P(FIRE) por ano alvo — dados de fire_matrix.by_profile[atual] + earliest_fire' },
  { datetime: '2026-04-30T20:30:00', type: 'layout', component: 'FirePage', tab: 'fire', anchor: 'section-scenario-compare', de: 'Tabela Base vs Aspiracional aninhada dentro da seção Cenários FIRE', para: 'C10: section-scenario-compare movida para antes de Coast FIRE e FIRE Spectrum (hierarquia mais clara: cenários numéricos antes de referências conceituais)' },
  { datetime: '2026-04-30T20:30:00', type: 'visual', component: 'FirePage', tab: 'fire', anchor: 'fire-number-meta', de: 'Gap G exibe barra de progresso visual + texto "FIRE Number = gastos / SWR" duplicando KpiHero', para: 'A7: barra de progresso removida do Gap G — KpiHero já mostra percentual; Gap G mantém valores absolutos (Meta/Atual/Gap em R$)' },
  { datetime: '2026-04-30T23:30:00', type: 'fix', component: 'SpendingSmile / chartSetup', tab: 'fire', anchor: '', de: 'Dois campos spending smile em data.json (spendingSmile legacy + spending_smile canonical)', para: 'spendingSmile (DEPRECATED) removido; chartSetup.ts usa spending_smile.*.gasto_lifestyle como canônico' },
  { datetime: '2026-04-30T23:00:00', type: 'dado', component: 'BondTentAnalysisSection', tab: 'backtest', anchor: 'bond-tent-analysis', de: 'Sem análise de Bond Tent no backtest', para: 'B9: seção colapsável com tent size (39% patrimônio), bond pool atual vs necessário, glide path 2026–2040 e gap RF' },
  { datetime: '2026-04-30T23:00:00', type: 'dado', component: 'RendaVsIpcaDuracaoSection', tab: 'simulators', anchor: 'sim-renda-vs-ipca-duracao', de: 'Sem comparação de duração Renda+2065 vs IPCA+2050', para: 'B13: seção colapsável com taxa, duration, spread, tradeoff longevidade/flexibilidade e impacto no bond pool' },
  { datetime: '2026-04-30T21:30:00', type: 'dado', component: 'CascadeSection', tab: 'simuladores', anchor: '', de: 'Cascade sem taxa de mercado por instrumento', para: 'B14: linha "Taxa: IPCA+X% · piso Y% · gap ±Zpp" em IPCA+Longo e Renda+' },
  { datetime: '2026-04-30T21:00:00', type: 'layout', component: 'ETFRegionComposition', tab: 'portfolio', anchor: '', de: 'Tab default SWRD', para: 'C2: tab default mudado para AVGS (mais diferenciado — mix EM/DM, não só global)' },
  { datetime: '2026-04-30T21:00:00', type: 'layout', component: 'ExpectedReturnWaterfall', tab: 'performance', anchor: 'section-expected-return-waterfall', de: 'CollapsibleSection collapsed por default', para: 'C1: defaultOpen=true — waterfall aberto por default na aba Performance' },
  { datetime: '2026-04-30T21:00:00', type: 'cálculo', component: 'SequenceOfReturnsRisk', tab: 'fire', anchor: 'sequence-returns', de: 'pisoEssencial hardcoded em 184000', para: 'A6: pisoEssencial usa gastoPiso da prop (data.gasto_piso = 180000) — zero hardcode' },
  { datetime: '2026-04-30T21:00:00', type: 'dado', component: 'PremisesTable', tab: 'performance', anchor: 'premissasVsRealizadoSection', de: 'Sem aviso de significância estatística', para: 'B4: nota "N = X anos — insuficiente para inferir significância de alpha (mínimo ~10 anos)"' },
  { datetime: '2026-04-30T20:00:00', type: 'dado', component: 'PerformancePage', tab: 'performance', anchor: '', de: 'Sem Tracking Error nem Information Ratio', para: 'B1: cards TE, IR e Alpha anualizado — calculados da série backtest.target vs shadowA (VWRA proxy)' },
  { datetime: '2026-04-30T20:00:00', type: 'dado', component: 'NowPage', tab: 'now', anchor: '', de: 'Sem semáforo de factor drought nem loadings agregados', para: 'C4+C5: strip compact — drought semáforo (verde/amarelo/vermelho) + Portfolio β SMB/HML/RMW ponderado por pesos IPS' },
  { datetime: '2026-04-30T20:00:00', type: 'visual', component: 'DecisaoDoMes', tab: 'now', anchor: '', de: 'Sem contexto fatorial na decisão de aporte', para: 'C6: linha "SWRD = market neutral · AVGS/AVEM = tilt value + profitability via Avantis" no banner ETF prioritário' },
  { datetime: '2026-04-30T20:00:00', type: 'dado', component: 'PortfolioPage', tab: 'portfolio', anchor: 'section-factor-loadings', de: 'drought_atual calculado como aproximação local', para: 'B7: drought_atual usa factor_rolling.drought_months canônico do pipeline' },
  { datetime: '2026-04-30T20:00:00', type: 'dado', component: 'PortfolioPage', tab: 'portfolio', anchor: 'section-factor-loadings', de: 'Monitoramento de drought apenas AVGS vs SWRD', para: 'B8: linha AVEM no counter de drought (usa avem_ytd_pct quando disponível, null-safe)' },
  { datetime: '2026-04-30T20:00:00', type: 'dado', component: 'PortfolioPage', tab: 'portfolio', anchor: 'section-factor-loadings', de: 'Sem percentil RMW no value spread widget', para: 'B5: RMW percentile via factor.value_spread.percentile_rmw ou SWRD loading fallback' },
  { datetime: '2026-04-30T20:00:00', type: 'dado', component: 'PortfolioPage', tab: 'portfolio', anchor: 'section-factor-loadings', de: 'Sem painel visual de factor loadings FF5 por ETF', para: 'B6: seção colapsável "Factor Loadings FF5 — por ETF" com barras SMB/HML/RMW/CMA e badge de significância' },
  { datetime: '2026-04-30T20:00:00', type: 'dado', component: 'ETFFactorComposition', tab: 'performance', anchor: 'section-etf-factor', de: 'RMW e CMA colapsados em "Quality" — perda de granularidade fatorial', para: 'A2: FF5 separado RMW (Profitability) e CMA (Investment); usa factor_loadings quando disponível; legenda FF5' },
  { datetime: '2026-04-30T20:00:00', type: 'visual', component: 'PerformancePage DeltaBarChart', tab: 'performance', anchor: 'section-factor-rolling', de: 'Sem referências de threshold no gráfico factor-rolling', para: 'B2: markLine +5pp (target premium verde) e -5pp (revisão vermelho) no gráfico rolling 12m' },
  { datetime: '2026-04-30T20:00:00', type: 'dado', component: 'PerformanceSummary', tab: 'performance', anchor: '', de: 'VWRA sem nota de que é benchmark secundário', para: 'B3: tooltip + rodapé ¹ explicitando SWRD como benchmark primário' },
  { datetime: '2026-04-30T19:00:00', type: 'gráfico', component: 'SpendingSmileChart', tab: 'fire', anchor: 'section-spending-smile', de: 'Spending smile ausente do dashboard', para: 'G4: barras lifestyle + saúde por fase go-go/slow-go/no-go — dados de fire_montecarlo.SPENDING_SMILE + SAUDE_BASE' },
  { datetime: '2026-04-30T18:00:00', type: 'dado', component: 'FireSimuladorSection', tab: 'simulators', anchor: '', de: 'Sem contexto de taxa RF no simulador', para: 'G12: slider IPCA+ taxa (4–8%) com P(FIRE) estimado por sensibilidade (Pfau 2012 heurístico)' },
  { datetime: '2026-04-30T18:00:00', type: 'gráfico', component: 'BacktestPage', tab: 'backtest', anchor: 'section-ntnb-history', de: 'Sem histórico de taxas IPCA+2040', para: 'G9: chart ECharts com taxa indicativa ANBIMA mensal desde Jan/2020, linha gatilho DCA 6%' },
  { datetime: '2026-04-30T18:00:00', type: 'visual', component: 'AlphaVsSWRDChart', tab: 'performance', anchor: 'section-alpha-swrd', de: 'Fallback silencioso com valores hardcoded quando backtest.metrics_by_period ausente', para: 'G8: banner "* Dados estimados" visível quando metrics_by_period indisponível' },
  { datetime: '2026-04-30T18:00:00', type: 'dado', component: 'HoldingsTable', tab: 'portfolio', anchor: '', de: 'Sem colunas TER e AUM na tabela de posições', para: 'G10+G11: colunas TER (%/ano) e AUM (€M) com semáforo verde/amarelo/vermelho por threshold IPS' },
  { datetime: '2026-04-30T18:00:00', type: 'dado', component: 'WithdrawPage', tab: 'withdraw', anchor: '', de: 'Sem card de status do bond pool', para: 'G7+G6: Bond Pool Status card — progresso atual + projeção 2040 com barra de progresso' },
  { datetime: '2026-04-30T18:00:00', type: 'dado', component: 'NowPage strip', tab: 'now', anchor: '', de: 'Sem indicadores de guardrail zone, factor signal ou AUM alert na tela principal', para: 'G13+G2+G1: strip compact — zona guardrail + SWR P50 + AVGS/SWRD YTD excess + alertas AUM' },
  { datetime: '2026-04-30T18:00:00', type: 'dado', component: 'KpiHero', tab: 'now', anchor: '', de: 'Sem card P(FIRE) base com fav/stress no hero', para: 'G3: card P(FIRE) com sub-linha fav X% · stress Y%' },
  { datetime: '2026-04-30T18:00:00', type: 'visual', component: 'SensitividadePFire', tab: 'fire', anchor: 'section-pfire-sensitivity', de: 'Sensitivity tornado colapsado por padrão', para: 'G5: defaultOpen=true — análise de sensibilidade visível imediatamente' },
  { datetime: '2026-04-30T13:00:00', type: 'fix', component: 'DecisaoDoMes', tab: 'now', anchor: 'section-decisao-mes', de: 'Coluna "E[R]" sem unidade/contexto', para: '"E[R] USD" com tooltip explicando retorno em USD real (não BRL)' },
  { datetime: '2026-04-30T12:00:00', type: 'fix', component: 'RebalancingStatus', tab: 'now', anchor: 'section-rebalancing', de: '"Vender {ticker}" quando drift > 0 — viola regra no-sell da IPS', para: '"Aguardar — X acima do alvo, aportar nos deficitários". Footer sem menção de IR em vendas.' },
  { datetime: '2026-04-30T12:00:00', type: 'fix', component: 'PFireHeroBanner', tab: 'fire', anchor: '', de: 'Label "P(FIRE 2040)" hardcoded', para: 'Label dinâmico usa premissas.fire_year_base do pipeline' },
  { datetime: '2026-04-30T12:00:00', type: 'fix', component: 'RendaFloorKatia', tab: 'fire', anchor: '', de: 'pfireCasal usa pfire_aspiracional como proxy incorreto', para: 'pfireCasal usa pfire_by_profile.casado.base (campo correto, null enquanto MC casal não rodou)' },
  { datetime: '2026-04-30T12:00:00', type: 'fix', component: 'FeeAnalysisCard', tab: 'performance', anchor: 'section-alpha-swrd', de: 'alphaLiquidoPctYear=0.16 hardcoded', para: 'Usa premissas.haircut_alpha_liquido × 100 do pipeline (McLean & Pontiff 2016)' },
  { datetime: '2026-04-30T00:00:00', type: 'fix', component: 'RFStatusPanel', tab: 'now', anchor: 'section-dca-status', de: 'DCA badge contradiz recomendação quando posição >= alvo', para: 'recomendação verifica posição antes de checar taxa' },
  { datetime: '2026-04-30T00:00:00', type: 'fix', component: 'AlphaVsSWRDChart', tab: 'performance', anchor: 'section-alpha-swrd', de: 'annualização alpha por média aritmética', para: 'média geométrica (compounding correto)' },
  { datetime: '2026-04-30T00:00:00', type: 'fix', component: 'TimeToFireProgressBar', tab: 'now', anchor: '', de: 'idade 39 hardcoded', para: 'usa premissas.idade_atual dinâmico' },
  { datetime: '2026-04-30T00:00:00', type: 'fix', component: 'CoastFireCard', tab: 'fire', anchor: 'section-coast-fire', de: 'aporte R$300k hardcoded', para: 'usa premissas.aporte_mensal × 12 dinâmico' },
  { datetime: '2026-04-30T00:04:00', type: 'visual', component: 'TrackingFireChart', tab: 'fire', anchor: 'section-fire-trilha', de: 'Sem contexto de origem das bandas FIRE', para: 'Notas compactas: origem acadêmica vs convenção de comunidade por banda' },
  { datetime: '2026-04-30T00:03:00', type: 'gráfico', component: 'TrackingFireChart', tab: 'fire', anchor: 'section-fire-trilha', de: 'Sem marcos de milestone FIRE', para: 'Marcos Barista/Lean/FIRE como linhas horizontais + markers no cruzamento do P50' },
  { datetime: '2026-04-30T00:02:00', type: 'visual', component: 'IifptPanel', tab: 'now', anchor: 'section-iifpt-radar', de: 'Score hero sem label "SCORE", /100 em linha separada', para: 'Score hero com label SCORE + /100 · planejamento alinhado ao WellnessScore' },
  { datetime: '2026-04-30T00:02:00', type: 'fix', component: 'Múltiplos', tab: 'now', anchor: '', de: 'Footers "Fonte:" com paths internos (json/py/md) visíveis no dashboard', para: 'Footers removidos ou sem referências a arquivos internos' },
  { datetime: '2026-04-30T00:01:00', type: 'fix', component: 'WellnessScore', tab: 'now', anchor: 'section-wellness', de: 'Coluna detail estreita; replaceAll faltando em humanCapitalStatus', para: 'Coluna w-28; solteiro sem dependentes exibe correto' },
  { datetime: '2026-04-30T00:01:00', type: 'visual', component: 'IifptPanel', tab: 'now', anchor: 'section-iifpt-radar', de: 'Título "Modelo IIFPT"; "——/100" com dashes', para: 'Nome completo IIFPT; "/100" sem dashes' },
  { datetime: '2026-04-30T00:00:00', type: 'visual', component: 'IifptPanel', tab: 'now', anchor: 'section-iifpt-radar', de: 'Siglas na tabela de interação (CF, RM)', para: 'Nomes completos (Cash Flow, Risk Mgmt)' },
  { datetime: '2026-04-30T23:45:00.000Z', type: 'visual', component: 'IifptPanel', tab: 'now', anchor: 'section-iifpt-radar', de: 'acionáveis sem prazo e sem prefixo Issue', para: 'CF mostra prazo até FIRE (~14a), RM e Estate prefixados com "Issue"' },
  // ── 2026-04-30 — IifptPanel completo ──
  { datetime: '2026-04-30T23:30:00.000Z', type: 'dado', component: 'IifptPanel', tab: 'now', anchor: 'section-iifpt-radar', de: 'radar simples com cobertura', para: 'Modelo IIFPT completo: score integrado, tabela de domínios com acionáveis, coupling table, callout RM' },
  // ── 2026-04-30 — radar IIFPT nomes completos + colapsado + remove regime badge ──
  { datetime: '2026-04-30T23:00:00.000Z', type: 'visual', component: 'IifptRadar / RegimeBadge', tab: 'now', anchor: 'section-iifpt-radar', de: 'regime badge inline + siglas no radar + defaultOpen=true', para: 'badge removido, radar colapsado por padrão, nomes completos (Investment/Retirement/Cash Flow/Risk Mgmt/Estate)' },
  // ── 2026-04-30 — IifptRadar defaultOpen=true ──
  { datetime: '2026-04-30T22:00:00.000Z', type: 'visual', component: 'IifptRadar', tab: 'now', anchor: 'section-iifpt-radar', de: 'colapsado por padrão (oculto)', para: 'aberto por padrão — seção Cobertura IIFPT visível ao acessar NOW tab' },
  // ── 2026-04-30 — fix changelog NOW tab links ──
  { datetime: '2026-04-30T21:00:00.000Z', type: 'fix', component: 'Changelog links (NOW tab)', tab: 'assumptions', anchor: '', de: 'links NOW tab apontando para #anchor (erro — âncora na página assumptions)', para: 'links NOW tab apontando corretamente para /#anchor' },
  // ── 2026-04-30 — BRFireSim polish ──
  { datetime: '2026-04-30T13:00:00.000Z', type: 'visual', component: 'BRFireSimChart / BRFireSimSection', tab: 'backtest', anchor: '', de: 'legend sem nomes FIRE, cores erradas no legend, cabeçalho só percentual', para: 'legend com "SWR X% · Nome FIRE" e cores explícitas por série; cabeçalho da tabela com percentual + nome FIRE; SWR_KEYS extraído para brfiresim-constants.ts' },
  // ── 2026-04-30 — DEV-iifpt-dashboard: CC1+DC1+DC2+DC3 ──
  { datetime: '2026-04-30T20:00:00.000Z', type: 'dado', component: 'IifptRadar', tab: 'now', anchor: 'section-iifpt-radar', de: 'ausente', para: 'Radar de cobertura IIFPT — 6 domínios (Inv/Ret/Tax/CF/RM/Est) vs pesos IPS. RM e Est destacados como gaps (<30%). Collapsible.' },
  { datetime: '2026-04-30T20:00:00.000Z', type: 'visual', component: 'RegimeVidaBadge', tab: 'now', anchor: '', de: 'ausente', para: 'Badge inline "Acumulação · r3 ~2034" no topo da seção Status. Azul=r2, laranja=r3, verde=r4.' },
  { datetime: '2026-04-30T20:00:00.000Z', type: 'dado', component: 'KpiHero', tab: 'now', anchor: '', de: 'sem nota de gaps IIFPT', para: 'Nota discreta "RM ❌ Est ⏳ não modelados" abaixo do card Progresso FIRE quando coverage < 30%.' },
  // ── 2026-04-30 — HD-gaps-aposenteaos40-spec: Feature 3 — Historical Cycle Simulation ──
  { datetime: '2026-04-30T12:30:00.000Z', type: 'dado', component: 'BRFireSimSection', tab: 'backtest', anchor: 'section-brfiresim', de: 'ausente', para: 'brFIRESim — Historical Cycle Simulation (Bengen/cFIREsim): 4 ciclos históricos de 20 anos, SWR 3-8%, caveat sanity-check proeminente' },
  // ── 2026-04-30 — HD-gaps-aposenteaos40-spec: Feature 2 — FIRE Spectrum Widget ──
  { datetime: '2026-04-30T12:00:00.000Z', type: 'dado', component: 'FireSpectrumWidget', tab: 'fire', anchor: 'section-fire-spectrum', de: 'ausente', para: 'FIRE Spectrum — Fat FIRE / FIRE / Lean FIRE / Barista FIRE com múltiplos e SWR implícito' },
  // ── 2026-04-30 — HD-gaps-aposenteaos40-spec: Feature 1 — Coast FIRE Calculator ──
  { datetime: '2026-04-30T12:00:00.000Z', type: 'dado', component: 'CoastFireCard', tab: 'fire', anchor: 'section-coast-fire', de: 'ausente', para: 'Coast FIRE Calculator — 3 cenários, progress bar, ano projetado' },
  // ── 2026-04-30 — Privacy audit: mask financeiro em 11 componentes ──
  { datetime: '2026-04-30T10:00:00.000Z', type: 'visual', component: 'Privacy (global)', tab: 'now', anchor: '', de: '24 leaks: CAGR, delta, vol, VaR, drift %, P(FIRE), P(qual), allocation % visíveis em privacy mode', para: 'v1.180.0 — Todos os valores financeiros mascarados (••%) em privacy mode: PerformanceSummary, PFireMonteCarloTornado, HODL11PositionPanel, BRLPurchasingPowerTimeline, DecisaoDoMes, TimelineChart, ReverseFire, fire/page, withdraw/page, portfolio/page, page' },
  // ── 2026-04-30 — P(quality) nos cards Base/Favorável/Stress do PFireMonteCarloTornado ──
  { datetime: '2026-04-30T02:00:00.000Z', type: 'dado', component: 'PFireMonteCarloTornado', tab: 'now', anchor: '', de: 'Cards BASE/FAVORÁVEL/STRESS mostrando apenas P(FIRE)', para: 'v1.172.0 — Cards mostram P(qual) por cenário: base=79.0%, fav=84.8%, stress=74.5%' },
  // ── 2026-04-30 — Simulador ReverseFire: seletor Sem bucket / Atual 24% / Full 100% em P(qualidade) ──
  { datetime: '2026-04-30T01:00:00.000Z', type: 'dado', component: 'ReverseFire', tab: 'fire', anchor: '', de: 'P(qualidade) exibindo apenas modo canônico (partial)', para: 'v1.167.0 — Simulador: seletor bond pool mode (Sem bucket / Atual 24% / Full 100%) em P(qualidade) do ReverseFire' },
  // ── 2026-04-30 — Matriz P(quality): seletores Sem bucket / Atual X% / Full 100% ──
  { datetime: '2026-04-30T00:00:00.000Z', type: 'dado', component: 'PQualityMatrix', tab: 'fire', anchor: 'pquality-matrix', de: 'Matriz P(quality) mostrando apenas modo canônico (partial)', para: 'v1.163.0 — Matriz P(quality): seletores Sem bucket / Atual 24% / Full 100% (135 calls, n_sim=1000 cada modo)' },
  // ── 2026-04-29 — P(quality) seletores proxy/partial/full no hero ──
  { datetime: '2026-04-29T23:00:00.000Z', type: 'dado', component: 'P(Quality) Hero Seletores', tab: 'fire', anchor: '', de: 'P(quality) hero mostrando apenas valor canônico (partial)', para: 'v1.162.0 — P(quality) seletores: proxy / partial / full no hero do dashboard FIRE. Full=88.7% base (potencial com bucket completo).' },
  // ── 2026-04-29 — Bond Pool partial isolation (FR-mc-bond-pool-partial-isolation) ──
  { datetime: '2026-04-29T22:00:00.000Z', type: 'cálculo', component: 'BondPoolIsolationBadge', tab: 'fire', anchor: '', de: 'Bond pool isolation binário: ativo somente quando >= 80% do target (~R$416k)', para: 'v1.161.0 — Bond pool partial isolation: vol e guardrails proporcionais à fração de cobertura do bucket. P(quality) mais preciso durante acumulação (atual: 24%). Badge distingue: verde (completo), amarelo (partial), cinza (sem pool)' },
  // ── 2026-04-29 — Bond Pool Isolation status badge (FR-mc-bond-pool-isolation) ──
  { datetime: '2026-04-29T18:00:00.000Z', type: 'dado', component: 'BondPoolIsolationBadge', tab: 'fire', anchor: '', de: 'Sem badge de bond pool isolation', para: 'Badge amarelo/verde mostrando completion % do bond pool e se P(quality) usa proxy ou isolation real' },
  // ── 2026-04-29 — P(quality) KpiHero + FireScenariosTable + WhatIf + ReverseFire ──
  { datetime: '2026-04-29T17:00:00.000Z', type: 'dado', component: 'KpiHero', tab: 'now', anchor: '', de: 'P(FIRE) aspiracional sem quality', para: 'P(quality) aspiracional adicionado ao KPI hero card' },
  { datetime: '2026-04-29T17:00:00.000Z', type: 'dado', component: 'FireScenariosTable', tab: 'fire', anchor: 'fire-scenarios', de: 'Tabela sem P(quality)', para: 'Coluna/linha P(quality) adicionada por cenário' },
  // ── 2026-04-29 — FR-pquality-matrix: Matriz 5 critérios × 3 perfis × 3 cenários ──
  { datetime: '2026-04-29T16:00:00.000Z', type: 'dado', component: 'PQualityMatrix', tab: 'fire', anchor: 'pquality-matrix', de: 'P(quality) único valor', para: 'Matriz 5 critérios × 3 perfis × 3 cenários de mercado; default muda para critério B (≤1 ano ruim no go-go)' },
  // ── 2026-04-29 — FR-pquality-recalibration: P(quality) hero + perfis + simulators ──
  { datetime: '2026-04-29T12:00:00', type: 'cálculo', component: 'P(Quality) Hero', tab: 'fire', anchor: '', de: 'não existia', para: 'banner hero exibe P(quality) com cor semáforo verde≥70%/amarelo≥55%/vermelho<55% — FR-pquality-recalibration 2026-04-29' },
  { datetime: '2026-04-29T12:00:00', type: 'cálculo', component: 'P(Quality) Perfis Familiares', tab: 'fire', anchor: 'section-pfire-familia', de: 'não existia', para: 'P(quality) por perfil (atual/casado/filho/aspiracional) com cor semáforo — piso 80% smile, min_frac 85% anos, go-go 10 anos — FR-pquality-recalibration' },
  { datetime: '2026-04-29T12:00:00', type: 'dado', component: 'P(Quality) Simuladores', tab: 'simulators', anchor: '', de: 'não existia', para: 'card P(quality) no resultado do simulador FIRE (lookup precomputado by_profile) — FR-pquality-recalibration 2026-04-29' },
  // ── 2026-04-29 — FR-pfire-model-robustness: intervalo de incerteza de modelo ──
  { datetime: '2026-04-29T07:47:00', type: 'dado', component: 'P(FIRE) Hero — Intervalo Incerteza', tab: 'fire', anchor: '', de: 'número pontual 83.7%', para: 'exibe "modelo: ~72–92%" abaixo do número central — FR-pfire-model-robustness (RF fix 6.0%→5.34%, iid assumption)' },
  // ── 2026-04-28 — Gap T: Widget Qualidade FIRE (p_quality) ──
  { datetime: '2026-04-28T22:00:00', type: 'dado', component: 'Gap T — Qualidade FIRE', tab: 'assumptions', anchor: 'assumptions-onde-estou', de: '—', para: 'card com P(quality)=64.3%, P(quality|surviving), piso go-go e slow-go (80% do gasto da fase) — FR-guardrails-categoria-elasticidade' },
  // ── 2026-04-28 — Gap W: Tracking Error Rolling 12m AVGS vs SWRD ──
  { datetime: '2026-04-28T23:45:00', type: 'gráfico', component: 'Factor Tracking Error Rolling 12m', tab: 'portfolio', anchor: '', de: '—', para: 'gráfico linha rolling 12m excess return AVGS vs SWRD (verde/amarelo -5pp/vermelho -10pp) + drought counter integrado como label — Gap W 2026-04-28' },
  // ── 2026-04-28 — Header: restaurar ícone Hammer na version pill ──
  { datetime: '2026-04-28T23:25:00', type: 'visual', component: 'Header — Version Pill', tab: 'now', anchor: '', de: 'sem ícone', para: 'ícone Hammer (9px) restaurado na tag de versão/build — perdido no merge da version pill' },
  // ── 2026-04-28 — Gap V: Projeção de Ativos Não-Financeiros (imóvel + terreno) ──
  { datetime: '2026-04-28T23:30:00', type: 'dado', component: 'Ativos Não-Financeiros — Projeção de Venda', tab: 'assumptions', anchor: 'non-financial-assets', de: '—', para: 'seção Gap V: imóvel (venda 2027, equity ~R$367k, IR 15%, FV@FIRE) + terreno (venda 2031, equity ~R$127.5k), total FV consolidado — upside não incluído no P(FIRE) baseline' },
  // ── 2026-04-28 — Gap U: Factor Value Spread widget (AQR HML Devil, proxy 58/42) ──
  { datetime: '2026-04-28T23:00:00', type: 'dado', component: 'Factor Value Spread', tab: 'portfolio', anchor: '', de: '—', para: 'widget semáforo value spread AVGS — AQR HML Devil + KF SMB, proxy 58/42, status P42 neutro (wide >P75, compressed <P25)' },
  // ── 2026-04-28 — ContributionReturnsCrossover: EC colors + axis theme padrão ──
  { datetime: '2026-04-28T22:45:00', type: 'visual', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: 'CSS vars (var(--muted), var(--yellow)) nas séries e eixos sem theme padrão', para: 'EC.muted / EC.yellow (hex canvas-safe), EC_AXIS_LINE + EC_SPLIT_LINE + EC_TOOLTIP + EC_AXIS_LABEL em todos os eixos' },
  // ── 2026-04-28 — ContributionReturnsCrossover: UI fixes (tooltip K, legenda bottom, banda, label) ──
  { datetime: '2026-04-28T22:30:00', type: 'visual', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: 'tooltip em M ("R$ R$0M"), legenda top, banda opacity 8%, sub-label "VALOR ABSOLUTO" desnecessário, card "Aporte Anual Modelo"', para: 'tooltip pvLabel() nativo (R$392k), legenda bottom, banda 15%, sub-label removido, card renomeado para "Aporte Anual"' },
  // ── 2026-04-28 — ContributionReturnsCrossover: remove flywheel (%) sub-chart ──
  { datetime: '2026-04-28T22:10:00', type: 'gráfico', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: '2 gráficos: Valor Absoluto R$ + Flywheel % do Patrimônio', para: '1 gráfico apenas: Valor Absoluto R$ — flywheel removido por decisão do FIRE agent (tendências díspares causavam confusão sem valor de decisão)' },
  // ── 2026-04-28 — ContributionReturnsCrossover: contexto histórico + estimativa 2026 ──
  { datetime: '2026-04-28T09:10:00', type: 'dado', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: '2026 como "parcial" sem distinção de tipo; 2021/2022 sem distinção de capital inicial; projeção sobrepunha 2026', para: '2026 como "estimado" (†) com nota Jan–Abr realizado + Mai–Dez @ R$25k/mês 9% nominal; 2021 capital_inicial=R$252k (XP), 2022 capital_inicial=R$72k (FIIs); projeção começa 2027; diamante amarelo nos anos com capital não-DCA; tooltip enriquecido' },
  // ── 2026-04-28 — ContributionReturnsCrossover: 4 fixes (legenda, toggle, 2026 parcial, ganho_rate 2021) ─
  { datetime: '2026-04-28T08:55:00', type: 'gráfico', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: 'legenda ausente, toggle residual, 2026 sem visual distinto, ganho_rate 2021 com denominador errado', para: 'legenda explícita (Rentabilidade Anual / Aportes Anuais), toggle removido do build, 2026* com opacidade 50% e aviso no tooltip, ganho_rate 2021=null no pipeline (linha % começa em 2022)' },
  // ── 2026-04-28 — ContributionReturnsCrossover: remove toggle + add flywheel chart ─
  { datetime: '2026-04-28T21:30:00', type: 'gráfico', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: 'toggle nominal/real + 1 chart R$ absoluto', para: 'sem toggle (nominal fixo), 2 charts: Valor Absoluto (R$) + Flywheel % do Patrimônio; pipeline adiciona aporte_rate e ganho_rate' },
  // ── 2026-04-28 — ContributionReturnsCrossover + P(FIRE) boxplot fix ─────────
  { datetime: '2026-04-28T20:00:00', type: 'gráfico', component: 'ContributionReturnsCrossover', tab: 'fire', anchor: 'section-contribuicao-retorno-crossover', de: 'não existia', para: 'Crossover Point — rentabilidade anual R$ vs aporte anual R$, histórico 2021-2026 + projeção 3 cenários, toggle nominal/real, marcador de crossover' },
  { datetime: '2026-04-28T20:00:00', type: 'dado', component: 'PFireDistribution', tab: 'fire', anchor: '', de: 'percentis bootstrap range 0.87pp (source: mc)', para: 'percentis por sensitivity_scenarios range 8pp (p5=82.1% p95=90.1%, source: sensitivity_scenarios)' },
  // ── 2026-04-28 — HD-dashboard-gaps-tier2 ────────────────────────────────────
  { datetime: '2026-04-28T16:00:00', type: 'dado', component: 'RendaPlusMtmPnl', tab: 'portfolio', anchor: 'section-renda-plus-mtm', de: 'sem MtM da Renda+', para: 'Gap S: card taxa entrada/atual + P&L MtM em R$ e % (data-testid="renda-plus-mtm-pnl")' },
  { datetime: '2026-04-28T18:00:00', type: 'visual', component: 'SpendingCeiling', tab: 'fire', anchor: 'section-spending-ceiling', de: 'valores em formato R$ 136.000', para: 'valores em formato compacto R$ 136k + valor mensal por card (R$ 11k/mês)' },
  { datetime: '2026-04-28T16:00:00', type: 'cálculo', component: 'BreakevenIpcaSelic', tab: 'portfolio', anchor: 'section-breakeven-ipca-selic', de: 'sem break-even IPCA+ vs Selic', para: 'Gap Q: break-even líquido de IR + tabela acumulação 10 anos (data-testid="breakeven-year-ipca-selic")' },
  { datetime: '2026-04-28T16:00:00', type: 'dado', component: 'VolRealizadaVsMC', tab: 'performance', anchor: '', de: 'sem vol realizada', para: 'Gap O: volatilidade anualizada 12m vs premissa MC com badge ⚠/✓ (data-testid="vol-realizada-vs-mc")' },
  { datetime: '2026-04-28T16:00:00', type: 'dado', component: 'BondPoolStatus', tab: 'fire', anchor: '', de: 'sem status bond pool', para: 'Gap M: progress bar IPCA+2040+2050 vs meta 7 anos de gastos (data-testid="bond-pool-status")' },
  { datetime: '2026-04-28T16:00:00', type: 'cálculo', component: 'RetornoCambialDecomposicao', tab: 'performance', anchor: '', de: 'sem decomposição cambial', para: 'Gap R: USD + FX = BRL com interpretação FX positivo/negativo (data-testid="retorno-cambial-decomposicao")' },
  { datetime: '2026-04-28T16:00:00', type: 'dado', component: 'SpendingCeiling', tab: 'fire', anchor: 'section-spending-ceiling', de: 'sem spending ceiling analítico', para: 'Gap L: 3 tiers P90/P85/P80 com SWR correspondente (data-testid="spending-ceiling")' },
  { datetime: '2026-04-28T16:00:00', type: 'cálculo', component: 'PFireSensitivity', tab: 'fire', anchor: 'section-pfire-sensitivity', de: 'sem tabela de sensibilidade P(FIRE)', para: 'Gap N: tabela 7 linhas com variável/base/stress/delta (data-testid="pfire-sensitivity-table")' },
  { datetime: '2026-04-28T16:00:00', type: 'dado', component: 'CorrelacaoStress', tab: 'portfolio', anchor: 'section-correlation-stress', de: 'sem correlação em stress', para: 'Gap P: normal vs stress (meses retorno<-5%) para equity-RF e equity-FX (data-testid="correlation-matrix-stress")' },
  // ── 2026-04-28 — HD-dashboard-gaps-tier1 ────────────────────────────────────
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'PatrimonioLiquidoIR', tab: 'now', anchor: 'section-patrimonio-liquido-ir', de: 'sem P(FIRE) líquido', para: 'Gap C: exibe P(FIRE) Líquido e Bruto de fire_montecarlo_liquido (data-testid="pfire-liquido")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'FIRENumberMeta', tab: 'fire', anchor: '', de: 'sem FIRE Number explícito', para: 'Gap G: FIRE Number com meta/atual/gap e barra de progresso (data-testid="fire-number-meta")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'RiskSemaforos', tab: 'now', anchor: 'risk-semaforos', de: '3 semáforos sem CDS', para: 'Gap B: CDS Brasil 5Y adicionado ao R2 como 4º semáforo (data-testid="cds-brasil-semaforo")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'BalancoHolistico', tab: 'now', anchor: 'section-balanco-holistico', de: 'balanço holístico só em FIRE tab', para: 'Gap A: seção colapsável no NOW tab com breakdown 5 componentes (data-testid="balanco-holistico")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'RendaPlusGatilho', tab: 'portfolio', anchor: '', de: 'sem widget dedicado Renda+', para: 'Gap D: widget taxa atual vs gatilho DCA com distância em bps e status (data-testid="renda-plus-gatilho")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'RendaFloorKatia', tab: 'fire', anchor: '', de: 'sem nota sobre renda Katia', para: 'Gap F: card Renda Floor Katia com INSS, P(FIRE) aspiracional e nota conservadora (data-testid="renda-floor-katia")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'FactorDroughtCounter', tab: 'portfolio', anchor: '', de: 'sem contador de drought fatorial', para: 'Gap H: badge AVGS vs SWRD com excess YTD, excess since launch e contexto histórico (data-testid="factor-drought-counter")' },
  { datetime: '2026-04-28T12:00:00', type: 'layout', component: 'ExposicaoGeografica', tab: 'portfolio', anchor: 'section-etf-region', de: 'data-testid="geo-donut"', para: 'Gap E: renomeado para data-testid="exposicao-geografica" (correto segundo spec)' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'DrawdownContextBanner', tab: 'performance', anchor: '', de: 'sem banner de drawdown contextual', para: 'Gap J: banner condicional quando drawdown>5% com guardrail e ação recomendada (data-testid="drawdown-context-banner")' },
  { datetime: '2026-04-28T12:00:00', type: 'dado', component: 'IPSSummary', tab: 'now', anchor: 'section-ips-summary', de: 'sem IPS summary', para: 'Gap K: card com 7 regras do IPS (equity alvo, SWR, pisos, guardrail, CDS, drift) de data.json (data-testid="ips-summary")' },
  // ── 2026-04-28 — risk_metrics fixes ─────────────────────────────────────────
  { datetime: '2026-04-28T00:00:00', type: 'cálculo', component: 'RiskDashboard', tab: 'portfolio', anchor: '', de: 'ModDur hardcoded 43.25, EQUITY_PCT hardcoded 0.79, semáforo drift hardcoded verde', para: 'ModDur lido de rf.renda2065.duration (fallback 46.24 ANBIMA), equity_pct de drift.atual, drift semáforo lê max deviation real' },
  { datetime: '2026-04-28T00:00:00', type: 'dado', component: 'RiskDashboard', tab: 'portfolio', anchor: 'section-duration-scenarios', de: 'tabela duration sem contexto proporcional; MtM exibido como % título sem % portfólio', para: 'coluna % do Portfólio (mtm × peso Renda+) + nota "posição tática ~3.4%"' },
  { datetime: '2026-04-28T00:00:00', type: 'dado', component: 'RiskDashboard', tab: 'fire', anchor: 'section-sorr-indicator', de: 'SoRR valores estáticos sem sinalização; baseline P(FIRE) implícito', para: 'caption "estimativa estática" + baseline dinâmico do MC (sorr_base_pfire)' },
  { datetime: '2026-04-28T00:00:00', type: 'dado', component: 'RiskDashboard', tab: 'portfolio', anchor: 'section-risk-contribution', de: 'nota de risco sem mencionar limitação metodológica', para: 'caption "Não considera correlação entre ativos"' },
  // ── 2026-04-27 — HD-risco-portfolio ─────────────────────────────────────────
  { datetime: '2026-04-27T00:00:00', type: 'gráfico', component: 'RiskDashboard', tab: 'now', anchor: '', de: 'sem visão de risco consolidada', para: 'Risk Score gauge + semáforos de alertas (R1+R2)' },
  { datetime: '2026-04-27T00:00:00', type: 'gráfico', component: 'RiskDashboard', tab: 'portfolio', anchor: '', de: 'sem visão de risco', para: 'Risk Contribution chart + Duration Scenarios table (R3+R4)' },
  { datetime: '2026-04-27T00:00:00', type: 'dado', component: 'RiskDashboard', tab: 'performance', anchor: '', de: 'sem monitor de drawdown', para: 'Drawdown Monitor com badge de guardrail (R5)' },
  { datetime: '2026-04-27T00:00:00', type: 'dado', component: 'RiskDashboard', tab: 'fire', anchor: '', de: 'sem indicador SoRR', para: 'SoRR Indicator com cenários de crash (R6)' },
  // ── 2026-04-27 ──────────────────────────────────────────────────────────────
  {
    datetime: '2026-04-27T20:48',
    type: 'layout',
    component: 'Retornos Mensais Heatmap',
    tab: 'performance',
    anchor: 'section-heatmap',
    de: 'posicionado após seção Análise Técnica',
    para: 'logo após Retornos Anuais',
  },
  {
    datetime: '2026-04-27T20:48',
    type: 'visual',
    component: 'SoRR — Texto Explicativo',
    tab: 'fire',
    anchor: 'sequence-returns',
    de: '3 parágrafos com referências Karsten + bond duration',
    para: '2 frases compactas (o quê é + 2 defesas)',
  },
  {
    datetime: '2026-04-27T20:35',
    type: 'dado',
    component: 'Exposição Cambial',
    tab: 'portfolio',
    anchor: 'section-brl-fx-portfolio',
    de: 'sempre 0%',
    para: 'computado de posições IBKR vivas',
  },
  {
    datetime: '2026-04-27T20:21',
    type: 'dado',
    component: 'DARF Obligations',
    tab: 'portfolio',
    anchor: 'section-darf-obligations',
    de: 'sem dados (vazio)',
    para: 'realized_pnl FIFO validado (IBKR Phase 3B)',
  },
  {
    datetime: '2026-04-27T20:04',
    type: 'gráfico',
    component: 'Stress Macroeconômico',
    tab: 'fire',
    anchor: 'section-stress-macro',
    de: 'não existia',
    para: 'card Stagflation & Hyperinflation com P(FIRE) e spending cut',
  },
  {
    datetime: '2026-04-27T20:01',
    type: 'cálculo',
    component: 'Fire Monte Carlo — Cenários',
    tab: 'fire',
    anchor: 'trackingFireSection',
    de: '2 cenários (base + IPCA+4)',
    para: '4 cenários (+ stagflation + hyperinflation)',
  },
  {
    datetime: '2026-04-27T18:56',
    type: 'dado',
    component: 'Factor Signal — Cache',
    tab: 'performance',
    anchor: 'section-etf-factor',
    de: 'sem timestamps, recalculado a cada run',
    para: 'timestamps + cache persistido em dados/',
  },
  {
    datetime: '2026-04-27T18:41',
    type: 'dado',
    component: 'P(FIRE) — Rastreabilidade',
    tab: 'fire',
    anchor: 'trackingFireSection',
    de: 'sem source / is_canonical',
    para: 'source + is_canonical em pfire_base e pfire_aspiracional',
  },
  {
    datetime: '2026-04-27T18:24',
    type: 'dado',
    component: 'Factor Signal + IR Diferido',
    tab: 'portfolio',
    anchor: 'section-tax-ir',
    de: 'ausentes em data.json',
    para: 'preenchidos (563 testes ✓)',
  },
  {
    datetime: '2026-04-27T18:08',
    type: 'gráfico',
    component: 'BTC/SWRD Correlation Chart',
    tab: 'backtest',
    anchor: 'section-btc-indicators',
    de: 'não existia',
    para: 'rolling 90d com série temporal real',
  },
  {
    datetime: '2026-04-27T17:55',
    type: 'dado',
    component: 'Decisão do Mês — Data',
    tab: 'now',
    anchor: '',
    de: '"Pendente (2026-03)"',
    para: 'data correta da última decisão aprovada',
  },
  {
    datetime: '2026-04-27T12:24',
    type: 'cálculo',
    component: 'Simuladores + FIRE Date + Attribution',
    tab: 'fire',
    anchor: 'fireAspirationalSection',
    de: 'P%, data FIRE e attribution com valores incorretos',
    para: 'todos corrigidos (v1.10.3)',
  },
  {
    datetime: '2026-04-27T10:26',
    type: 'dado',
    component: 'RF + CAGR Real + Drawdown + Imóvel',
    tab: 'performance',
    anchor: 'performanceSummarySection',
    de: 'RF Nubank, CAGR real, drawdown_extended, imóvel equity ausentes',
    para: 'todos preenchidos (v1.8.3)',
  },
  // ── 2026-04-25 ──────────────────────────────────────────────────────────────
  {
    datetime: '2026-04-25T21:12',
    type: 'gráfico',
    component: 'SoRR Heatmap — Monte Carlo',
    tab: 'fire',
    anchor: 'sequence-returns',
    de: 'placeholder vazio',
    para: 'trajetórias MC p10/p25/p50/p75/p90',
  },
  {
    datetime: '2026-04-25T21:10',
    type: 'dado',
    component: 'Focus Expectations BCB',
    tab: 'assumptions',
    anchor: 'assumptions-onde-estou',
    de: 'não existia',
    para: 'expectativas BCB Focus (IPCA, Selic, PIB, câmbio)',
  },
  {
    datetime: '2026-04-25T21:09',
    type: 'dado',
    component: 'BTC/SWRD Correlação 90d',
    tab: 'portfolio',
    anchor: 'section-crypto-band',
    de: 'não existia',
    para: 'correlação 90d exibida no painel de risco',
  },
  {
    datetime: '2026-04-25T21:06',
    type: 'visual',
    component: 'Factor Waterfall — Alpha Drought',
    tab: 'performance',
    anchor: 'section-expected-return-waterfall',
    de: 'sem nota de ressalva',
    para: 'caveat "alpha drought 2024–2025" adicionado',
  },
  {
    datetime: '2026-04-25T20:50',
    type: 'dado',
    component: 'RF Status Panel — pctAlvo',
    tab: 'portfolio',
    anchor: 'section-rf-status',
    de: 'hardcoded',
    para: 'dinâmico (taxa ANBIMA atual)',
  },
  {
    datetime: '2026-04-25T20:43',
    type: 'cálculo',
    component: 'P(FIRE) Aspiracional',
    tab: 'fire',
    anchor: 'fireAspirationalSection',
    de: 'incorreto (sem safety net)',
    para: 'corrigido + safety net documentado',
  },
  {
    datetime: '2026-04-25T17:14',
    type: 'cálculo',
    component: 'Aporte Médio',
    tab: 'now',
    anchor: 'section-rebalancing-status',
    de: 'R$68k (dupla contagem equity)',
    para: 'R$48k corrigido',
  },
  {
    datetime: '2026-04-25T18:17',
    type: 'layout',
    component: 'CollapsibleSection — Hash Navigation',
    tab: 'now',
    anchor: '',
    de: 'não abria ao navegar por URL âncora',
    para: 'auto-abre quando URL contém o hash da seção',
  },
  // ── 2026-04-24 ──────────────────────────────────────────────────────────────
  {
    datetime: '2026-04-24T23:08',
    type: 'layout',
    component: 'Decisão do Mês — Unificação',
    tab: 'now',
    anchor: '',
    de: '3 painéis separados (Aporte, DCA, Macro)',
    para: 'DecisaoDoMes unificado em 1 card',
  },
  {
    datetime: '2026-04-24T22:55',
    type: 'dado',
    component: 'Tabela Retornos Anuais',
    tab: 'performance',
    anchor: 'timelineSection',
    de: 'apenas retorno BRL por ano',
    para: '+ CAGR USD, VWRA e CDI por linha',
  },
  {
    datetime: '2026-04-24T22:34',
    type: 'dado',
    component: 'Portfolio — Binance + HODL11',
    tab: 'portfolio',
    anchor: 'section-etf-region',
    de: 'Binance sem posição real; HODL11 sem região',
    para: 'Binance integrado + HODL11 reclassificado como global',
  },
  {
    datetime: '2026-04-24T14:52',
    type: 'layout',
    component: 'FIRE Progress Card',
    tab: 'now',
    anchor: 'section-wellness',
    de: 'TimeToFire + FireProgressWellness separados',
    para: 'card único consolidado',
  },
  {
    datetime: '2026-04-24T14:45',
    type: 'dado',
    component: 'Semáforo de Saúde',
    tab: 'now',
    anchor: 'section-wellness',
    de: 'badge de status sem ação',
    para: '+ ação explícita + reorganização da home',
  },
  {
    datetime: '2026-04-24T13:21',
    type: 'cálculo',
    component: 'ReverseFire — Câmbio',
    tab: 'fire',
    anchor: 'fireAspirationalSection',
    de: 'câmbio fixo hardcoded',
    para: 'PTAX dinâmico integrado',
  },
  {
    datetime: '2026-04-24T10:32',
    type: 'cálculo',
    component: 'Monte Carlo P(FIRE) — Modelo',
    tab: 'fire',
    anchor: 'trackingFireSection',
    de: 'bootstrap heurístico',
    para: 'lognormal GBM + Ito correction (canônico)',
  },
  {
    datetime: '2026-04-24T10:12',
    type: 'gráfico',
    component: 'ReverseFire v2',
    tab: 'fire',
    anchor: 'fireAspirationalSection',
    de: 'v1 — forward sim simples',
    para: 'v2 — P(FIRE) MC + slider custo + ano no eixo',
  },
  {
    datetime: '2026-04-24T09:31',
    type: 'layout',
    component: 'Autenticação',
    tab: 'now',
    anchor: '',
    de: 'GitHub OAuth',
    para: 'SHA-256 + cookies (persistência iOS/remoto)',
  },
];
