// Dashboard Changelog — rastreamento de alterações visíveis no dashboard
// REGRA: antes de qualquer commit em react-app/src/, o dev agent DEVE adicionar
// entrada aqui (mais recente no topo). Veja CLAUDE.md → Changelog de Componentes.

export type ChangeType = 'layout' | 'dado' | 'gráfico' | 'cálculo' | 'visual';

export interface ChangelogEntry {
  datetime: string;   // ISO '2026-04-27T20:48'
  type: ChangeType;
  component: string;  // nome legível do componente
  tab: string;        // rota sem barra: 'performance' | 'fire' | 'backtest' | 'portfolio' | 'withdraw' | 'assumptions' | 'now'
  anchor: string;     // id da seção, sem '#' (vazio = só a aba)
  de: string;         // estado anterior
  para: string;       // estado novo
}

export const CHANGELOG: ChangelogEntry[] = [
  // ── 2026-04-27 ──────────────────────────────────────────────────────────────
  {
    datetime: '2026-04-27T20:48',
    type: 'layout',
    component: 'Retornos Mensais Heatmap',
    tab: 'performance',
    anchor: 'section-heatmap',
    de: 'posicionado após seção Análise Técnica',
    para: 'logo após Retornos Anuais',
  },
  {
    datetime: '2026-04-27T20:48',
    type: 'visual',
    component: 'SoRR — Texto Explicativo',
    tab: 'fire',
    anchor: 'sequence-returns',
    de: '3 parágrafos com referências Karsten + bond duration',
    para: '2 frases compactas (o quê é + 2 defesas)',
  },
  {
    datetime: '2026-04-27T20:35',
    type: 'dado',
    component: 'Exposição Cambial',
    tab: 'portfolio',
    anchor: 'section-brl-fx-portfolio',
    de: 'sempre 0%',
    para: 'computado de posições IBKR vivas',
  },
  {
    datetime: '2026-04-27T20:21',
    type: 'dado',
    component: 'DARF Obligations',
    tab: 'portfolio',
    anchor: 'section-darf-obligations',
    de: 'sem dados (vazio)',
    para: 'realized_pnl FIFO validado (IBKR Phase 3B)',
  },
  {
    datetime: '2026-04-27T20:04',
    type: 'gráfico',
    component: 'Stress Macroeconômico',
    tab: 'fire',
    anchor: 'section-stress-macro',
    de: 'não existia',
    para: 'card Stagflation & Hyperinflation com P(FIRE) e spending cut',
  },
  {
    datetime: '2026-04-27T20:01',
    type: 'cálculo',
    component: 'Fire Monte Carlo — Cenários',
    tab: 'fire',
    anchor: 'trackingFireSection',
    de: '2 cenários (base + IPCA+4)',
    para: '4 cenários (+ stagflation + hyperinflation)',
  },
  {
    datetime: '2026-04-27T18:56',
    type: 'dado',
    component: 'Factor Signal — Cache',
    tab: 'performance',
    anchor: 'section-etf-factor',
    de: 'sem timestamps, recalculado a cada run',
    para: 'timestamps + cache persistido em dados/',
  },
  {
    datetime: '2026-04-27T18:41',
    type: 'dado',
    component: 'P(FIRE) — Rastreabilidade',
    tab: 'fire',
    anchor: 'trackingFireSection',
    de: 'sem source / is_canonical',
    para: 'source + is_canonical em pfire_base e pfire_aspiracional',
  },
  {
    datetime: '2026-04-27T18:24',
    type: 'dado',
    component: 'Factor Signal + IR Diferido',
    tab: 'portfolio',
    anchor: 'section-tax-ir',
    de: 'ausentes em data.json',
    para: 'preenchidos (563 testes ✓)',
  },
  {
    datetime: '2026-04-27T18:08',
    type: 'gráfico',
    component: 'BTC/SWRD Correlation Chart',
    tab: 'backtest',
    anchor: 'section-btc-indicators',
    de: 'não existia',
    para: 'rolling 90d com série temporal real',
  },
  {
    datetime: '2026-04-27T17:55',
    type: 'dado',
    component: 'Decisão do Mês — Data',
    tab: 'now',
    anchor: '',
    de: '"Pendente (2026-03)"',
    para: 'data correta da última decisão aprovada',
  },
  {
    datetime: '2026-04-27T12:24',
    type: 'cálculo',
    component: 'Simuladores + FIRE Date + Attribution',
    tab: 'fire',
    anchor: 'fireAspirationalSection',
    de: 'P%, data FIRE e attribution com valores incorretos',
    para: 'todos corrigidos (v1.10.3)',
  },
  {
    datetime: '2026-04-27T10:26',
    type: 'dado',
    component: 'RF + CAGR Real + Drawdown + Imóvel',
    tab: 'performance',
    anchor: 'performanceSummarySection',
    de: 'RF Nubank, CAGR real, drawdown_extended, imóvel equity ausentes',
    para: 'todos preenchidos (v1.8.3)',
  },
  // ── 2026-04-25 ──────────────────────────────────────────────────────────────
  {
    datetime: '2026-04-25T21:12',
    type: 'gráfico',
    component: 'SoRR Heatmap — Monte Carlo',
    tab: 'fire',
    anchor: 'sequence-returns',
    de: 'placeholder vazio',
    para: 'trajetórias MC p10/p25/p50/p75/p90',
  },
  {
    datetime: '2026-04-25T21:10',
    type: 'dado',
    component: 'Focus Expectations BCB',
    tab: 'assumptions',
    anchor: 'assumptions-onde-estou',
    de: 'não existia',
    para: 'expectativas BCB Focus (IPCA, Selic, PIB, câmbio)',
  },
  {
    datetime: '2026-04-25T21:09',
    type: 'dado',
    component: 'BTC/SWRD Correlação 90d',
    tab: 'portfolio',
    anchor: 'section-crypto-band',
    de: 'não existia',
    para: 'correlação 90d exibida no painel de risco',
  },
  {
    datetime: '2026-04-25T21:06',
    type: 'visual',
    component: 'Factor Waterfall — Alpha Drought',
    tab: 'performance',
    anchor: 'section-expected-return-waterfall',
    de: 'sem nota de ressalva',
    para: 'caveat "alpha drought 2024–2025" adicionado',
  },
  {
    datetime: '2026-04-25T20:50',
    type: 'dado',
    component: 'RF Status Panel — pctAlvo',
    tab: 'portfolio',
    anchor: 'section-rf-status',
    de: 'hardcoded',
    para: 'dinâmico (taxa ANBIMA atual)',
  },
  {
    datetime: '2026-04-25T20:43',
    type: 'cálculo',
    component: 'P(FIRE) Aspiracional',
    tab: 'fire',
    anchor: 'fireAspirationalSection',
    de: 'incorreto (sem safety net)',
    para: 'corrigido + safety net documentado',
  },
  {
    datetime: '2026-04-25T17:14',
    type: 'cálculo',
    component: 'Aporte Médio',
    tab: 'now',
    anchor: 'section-rebalancing-status',
    de: 'R$68k (dupla contagem equity)',
    para: 'R$48k corrigido',
  },
  {
    datetime: '2026-04-25T18:17',
    type: 'layout',
    component: 'CollapsibleSection — Hash Navigation',
    tab: 'now',
    anchor: '',
    de: 'não abria ao navegar por URL âncora',
    para: 'auto-abre quando URL contém o hash da seção',
  },
  // ── 2026-04-24 ──────────────────────────────────────────────────────────────
  {
    datetime: '2026-04-24T23:08',
    type: 'layout',
    component: 'Decisão do Mês — Unificação',
    tab: 'now',
    anchor: '',
    de: '3 painéis separados (Aporte, DCA, Macro)',
    para: 'DecisaoDoMes unificado em 1 card',
  },
  {
    datetime: '2026-04-24T22:55',
    type: 'dado',
    component: 'Tabela Retornos Anuais',
    tab: 'performance',
    anchor: 'timelineSection',
    de: 'apenas retorno BRL por ano',
    para: '+ CAGR USD, VWRA e CDI por linha',
  },
  {
    datetime: '2026-04-24T22:34',
    type: 'dado',
    component: 'Portfolio — Binance + HODL11',
    tab: 'portfolio',
    anchor: 'section-etf-region',
    de: 'Binance sem posição real; HODL11 sem região',
    para: 'Binance integrado + HODL11 reclassificado como global',
  },
  {
    datetime: '2026-04-24T14:52',
    type: 'layout',
    component: 'FIRE Progress Card',
    tab: 'now',
    anchor: 'section-wellness',
    de: 'TimeToFire + FireProgressWellness separados',
    para: 'card único consolidado',
  },
  {
    datetime: '2026-04-24T14:45',
    type: 'dado',
    component: 'Semáforo de Saúde',
    tab: 'now',
    anchor: 'section-wellness',
    de: 'badge de status sem ação',
    para: '+ ação explícita + reorganização da home',
  },
  {
    datetime: '2026-04-24T13:21',
    type: 'cálculo',
    component: 'ReverseFire — Câmbio',
    tab: 'fire',
    anchor: 'fireAspirationalSection',
    de: 'câmbio fixo hardcoded',
    para: 'PTAX dinâmico integrado',
  },
  {
    datetime: '2026-04-24T10:32',
    type: 'cálculo',
    component: 'Monte Carlo P(FIRE) — Modelo',
    tab: 'fire',
    anchor: 'trackingFireSection',
    de: 'bootstrap heurístico',
    para: 'lognormal GBM + Ito correction (canônico)',
  },
  {
    datetime: '2026-04-24T10:12',
    type: 'gráfico',
    component: 'ReverseFire v2',
    tab: 'fire',
    anchor: 'fireAspirationalSection',
    de: 'v1 — forward sim simples',
    para: 'v2 — P(FIRE) MC + slider custo + ano no eixo',
  },
  {
    datetime: '2026-04-24T09:31',
    type: 'layout',
    component: 'Autenticação',
    tab: 'now',
    anchor: '',
    de: 'GitHub OAuth',
    para: 'SHA-256 + cookies (persistência iOS/remoto)',
  },
];
