var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/portfolio/page.js")
R.c("server/chunks/ssr/124y_next_dist_esm_0ne0xg_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01-j1bh._.js")
R.c("server/chunks/ssr/124y_next_dist_esm_0l.tyw5._.js")
R.c("server/chunks/ssr/124y_next_dist_compiled_0-geulf._.js")
R.c("server/chunks/ssr/124y_next_dist_server_route-modules_app-page_0wpcigd._.js")
R.c("server/chunks/ssr/[externals]__0n13xf4._.js")
R.c("server/chunks/ssr/react-app_0dqtp9z._.js")
R.c("server/chunks/ssr/124y_next_dist_client_components_0f.fdho._.js")
R.c("server/chunks/ssr/124y_next_dist_client_components_builtin_forbidden_0ju6p.g.js")
R.c("server/chunks/ssr/124y_next_dist_client_components_builtin_unauthorized_0aj5wz-.js")
R.c("server/chunks/ssr/124y_next_dist_client_components_builtin_global-error_12hn4t_.js")
R.c("server/chunks/ssr/react-app__next-internal_server_app_portfolio_page_actions_0xl_ce..js")
R.m("[project]/react-app/node_modules/next/dist/esm/build/templates/app-page.js?page=/portfolio/page { MODULE_0 => \"[project]/react-app/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/react-app/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/react-app/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/react-app/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/react-app/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/react-app/src/app/portfolio/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/react-app/node_modules/next/dist/esm/build/templates/app-page.js?page=/portfolio/page { MODULE_0 => \"[project]/react-app/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/react-app/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/react-app/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/react-app/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/react-app/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/react-app/src/app/portfolio/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
